services:
  postgres:
    container_name: postgres
    image: postgres:13
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./backend/dockerConfig/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:6-alpine
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379

  backend:
    container_name: bookstore_backend
    restart: always
    depends_on:
      - postgres
      - redis

    build:
      context: ./backend
      target: dependencies
    ports:
      - 3333:3333
      - 9229:9229
    env_file:
      - ./backend/.env
    environment:
      PG_HOST: postgres
      REDIS_HOST: redis
    volumes:
      - ./backend:/home/node/app
    command: dumb-init node --inspect=0.0.0.0 ace serve --watch

  frontend:
    container_name: bookstore_frontend
    build:
      context: ./frontend
    ports:
      - 4200:80
    depends_on:
      - backend

volumes:
  postgres_volume:
  redis_volume: